export enum CellNumber {
  Zero,
  One,
  Two,
  Tree,
  Four,
  Five,
  Six,
  Seven,
  Eight,
  Nine,
  Ten,
  Eleven,
  Twelve,
  Thirteen,
  Fourteen,
  Fiveteen,
  Sixteen,
  Seventeen,
  Eighteen,
  Nineteen,
  Twenty,
  TwentyOne,
  TwentyTwo,
  TwentyTree,
  TwentyFour,
  TwentyFive,
  TwentySix,
  TwentySeven,
  TwentyEight,
  TwentyNine,
  Thirty,
  ThirtyOne,
  ThirtyTwo,
  ThirtyThree,
  ThirtyFour,
  ThirtyFive,
  ThirtySix,
  DoubleZero
}

export type RouletteCells = {
  number: CellNumber;
  row: number;
  column: number;
}

export const RouletteCellsBuilder: Array<RouletteCells> = [
  { number: CellNumber.Zero, row: 2, column: 0 },
  { number: CellNumber.TwentyEight, row: 1, column: 13 },
  { number: CellNumber.Nine, row: 0, column: 4 },
  { number: CellNumber.TwentySix, row: 1, column: 12 },
  { number: CellNumber.Thirty, row: 0, column: 14 },
  { number: CellNumber.Eleven, row: 1, column: 5 },
  { number: CellNumber.Seven, row: 0, column: 3 },
  { number: CellNumber.Twenty, row: 1, column: 9 },
  { number: CellNumber.ThirtyTwo, row: 0, column: 15 },
  { number: CellNumber.Seventeen, row: 1, column: 8 },
  { number: CellNumber.Five, row: 0, column: 2 },
  { number: CellNumber.TwentyTwo, row: 1, column: 10 },
  { number: CellNumber.ThirtyFour, row: 0, column: 16 },
  { number: CellNumber.Fiveteen, row: 1, column: 7 },
  { number: CellNumber.Tree, row: 0, column: 1 },
  { number: CellNumber.TwentyFour, row: 1, column: 11 },
  { number: CellNumber.ThirtySix, row: 0, column: 17 },
  { number: CellNumber.Thirteen, row: 1, column: 6 },
  { number: CellNumber.One, row: 0, column: 0 },
  { number: CellNumber.DoubleZero, row: 2, column: 1 },
  { number: CellNumber.TwentySeven, row: 0, column: 13 },
  { number: CellNumber.Ten, row: 1, column: 4 },
  { number: CellNumber.TwentyFive, row: 0, column: 12 },
  { number: CellNumber.TwentyNine, row: 1, column: 14 },
  { number: CellNumber.Twelve, row: 0, column: 5 },
  { number: CellNumber.Eight, row: 1, column: 3 },
  { number: CellNumber.Nineteen, row: 0, column: 9 },
  { number: CellNumber.ThirtyOne, row: 1, column: 15 },
  { number: CellNumber.Eighteen, row: 0, column: 8 },
  { number: CellNumber.Six, row: 1, column: 2 },
  { number: CellNumber.TwentyOne, row: 0, column: 10 },
  { number: CellNumber.ThirtyThree, row: 1, column: 16 },
  { number: CellNumber.Sixteen, row: 0, column: 7 },
  { number: CellNumber.Four, row: 1, column: 1 },
  { number: CellNumber.TwentyTree, row: 0, column: 11 },
  { number: CellNumber.ThirtyFive, row: 1, column: 17 },
  { number: CellNumber.Fourteen, row: 0, column: 6 },
  { number: CellNumber.Two, row: 1, column: 0 },
];
